<?php

/**
 * @file
 * Contains efiara.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function efiara_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the efiara module.
    case 'help.page.efiara':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('E-fiara Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function efiara_theme() {
  return [
    'efiara' => [
      'render element' => 'children',
    ],
  ];
}
